---
- name: "Configure alacritty for user"
  copy:
    src: "{{ playbook_dir }}/roles/alacritty-config/files/alacritty"
    dest: "{{ ansible_env.HOME }}/.config/"

- name: ensures /root/.conf dir exists
  file: 
    path: "/root/.conf"
    state: directory

- name: "Configure alacritty for root"
  copy:
    src: "{{ playbook_dir }}/roles/alacritty-config/files/alacritty"
    dest: "/root/.config/"
