---
- name: "Apt update"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Basic tools"
  package:
    name:
      - git
      - curl
      - unzip
      - fontconfig
      - build-essential
      - xorg
      - dmenu
      - nsxiv  # image viewer
      - hexyl  # hex viewer
      - bat    # cat but with colors
      - neovim # NeoVIM
      - fzf    # fuzzy finder
      - virtualbox-guest-x11
    state: latest
  become: true
  become_method: sudo
  