---
- name: "Apt update"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Basic tools"
  package:
    name:
      - git
      - curl
      - unzip
      - fontconfig
      - build-essential
      - xorg
      - nsxiv
      - virtualbox-guest-x11
      # GUI
      #- lxappearance
      #- kali-themes
      #- qt5ct
    state: latest
  become: true
  become_method: sudo
  