---
- name: "Install FiraCode Nerd font"
  copy:
    src: "{{ playbook_dir }}/roles/wm/files/FiraCode"
    dest: "/usr/share/fonts/truetype/"
  become: true
  become_method: sudo

- name: "Install unifont and noto-emoji"
  package:
    name:
      - fonts-noto-color-emoji
      - unifont
    state: latest
  become: true
  become_method: sudo

- name: "Cache fonts"
  shell: |
    fc-cache -fv
