---
- name: "Install ly requirements"
  package:
    name:
      - libpam0g-dev
      - libxcb-xkb-dev
    state: latest
  become: true
  become_method: sudo

- name: "Download ly"
  git:
    repo: "https://github.com/fairyglade/ly"
    dest: "/tmp/ly"

- name: "Build ly"
  shell: |
    cd /tmp/ly
    make
    make install installsystemd
    systemctl enable ly.service
  become: true
  become_method: sudo
