---
- name: "dwm requirements"
  package:
    name:
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - libx11-xcb-dev
      - libxcb-res0-dev
    state: latest
  become: true
  become_method: sudo

