---
- name: Download rust installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  shell: /tmp/sh.rustup.rs -y

- name: install alacritty dependencies
  package:
    name:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3
    state: latest
  become: true
  become_method: sudo

- name: "Download alacritty"
  git:
    repo: "https://github.com/alacritty/alacritty"
    dest: "/tmp/alacritty"

- name: "Build alacritty"
  shell: |
    cd /tmp/alacritty
    cargo build --release

- name: "Copy binary to /usr/local/bin"
  copy:
    src: "/tmp/alacritty/target/release/alacritty"
    dest: "/usr/local/bin/alacritty"
    mode: 0755
  become: true
  become_method: sudo
