---
- name: "Configure alacritty for user"
  copy:
    src: "{{ playbook_dir }}/roles/wm-config/files/alacritty"
    dest: "{{ ansible_env.HOME }}/.config/"

- name: "ensures /root/.config dir exists"
  file: 
    path: "/root/.config"
    state: directory
  become: true
  become_method: sudo

- name: "Configure alacritty for root"
  copy:
    src: "{{ playbook_dir }}/roles/wm-config/files/alacritty"
    dest: "/root/.config/"
  become: true
  become_method: sudo