---
- name: "ensures {{ ansible_env.HOME }}/.local/share/dwm dir exists"
  file: 
    path: "{{ ansible_env.HOME }}/.local/share/dwm"
    recurse: true
    state: directory
  
- name: "Create {{ ansible_env.HOME }}/.local/share/dwm/autostart.sh"
  copy:
    src: "{{ playbook_dir }}/roles/wm-config/files/autostart.sh"
    dest: "{{ ansible_env.HOME }}/.local/share/dwm/"
    mode: 0755
