---
- name: "ensures {{ ansible_env.HOME }}/.local/share/dwm dir exists"
  file: 
    path: "{{ ansible_env.HOME }}/.local/share/dwm"
    recurse: true
    state: directory

- name: "Copy wallpapers"
  copy:
    src: "{{ playbook_dir }}/roles/wm-config/files/wallpaper.png"
    dest: "/usr/local/share/"
  become: true
  become_method: sudo
  
- name: "Create ~/.local/share/dwm/autostart.sh"
  copy:
    src: "{{ playbook_dir }}/roles/wm-config/files/autostart.sh"
    dest: "{{ ansible_env.HOME }}/.local/share/dwm/"
